var locations = ["Paris", "Machu Picchu", "Tokyo", "Sydney", "Rio de Janeiro"];
console.log("Original Order: ", locations);
console.log("Alphabetical Order: ", locations.sort());
console.log("Original Order: ", locations);
console.log("Reverse Alphabetical Order: ", locations.sort().reverse());
console.log("Original Order: ", locations);
locations.reverse();
console.log("Reversed Order: ", locations);
locations.reverse();
console.log("Original Order: ", locations);
locations.sort();
console.log("Alphabetical Order: ", locations);
locations.sort().reverse();
console.log("Reverse Alphabetical Order: ", locations);
