var car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car == 'Toyota'? I predict False.");
console.log(car == 'Toyota');
console.log("Is car == 'subaru'? I predict True.");
console.log(car === 'subaru');
console.log("Is car === 'Toyota'? I predict False.");
console.log(car === 'Toyota');
console.log("Is car != 'Toyota'? I predict True.");
console.log(car != 'Toyota');
console.log("Is car > 'toyota'? I predict False.");
console.log(car > 'toyota');
console.log("Is car < 'Tesla'? I predict True.");
console.log(car < 'Tesla');
console.log("Is car > 'audi'? I predict True.");
console.log(car > 'audi');
console.log("Is car.length == 6? I predict True.");
console.log(car.length == 6);
console.log("Is car[0] == 's'? I predict True.");
console.log(car[0] == 's');
